import os

MAX_PLAN_ATTEMPTS = 2
MAX_GENERATION_ATTEMPTS = 2
MAX_EXECUTION_RETRIES = 1
MAX_HEALING_ATTEMPTS = 1
MAX_FINAL_REPLANS = 1
RUN_TIMEOUT_SECONDS = 600
MAX_LLM_CALLS = int(os.getenv("QA_V2_MAX_LLM_CALLS", "8"))
